#
# ShowErrorsInClient: toggle that determines if permissions or other error messages
#                     are displayed client-side
#
# Allowed values : Yes (shows errors to players)
#                  No  (errors only show up in server console)
# 
ShowErrorsInClient: Yes

#
# DropInterval: length of time, in seconds, between drops
#
# Allowed values: numbers bigger than 1 (no decimals)
# 
DropInterval: 60

#
# FertilizerItem: item used in game to fertilize a tree 
#
# Allowed values: any item id or item name (default is bone_meal)
# 
FertilizerItem: bone_meal

#
# MaxTreesPerPlayer: optional parameter, maximum number of trees a player can plant 
#                    
# Allowed values: any integer bigger than 1 (set to -1 to disable, or comment out the parameter)
# 
#MaxTreesPerPlayer: 10

#
# MaxIsPerWorld: optional parameter, determines if MaxTreesPerPlayer setting is server wide or per world
#                defaults to "No" 
#                    
# Allowed values : Yes (players can plant MaxTreesPerPlayer trees in each world)
#                  No  (players can plant MaxTreesPerPlayer regardless of which world they are planted in)
# 
#MaxIsPerWorld: No

#
# WandItem: item used in game to see what type a tree is and if it needs fertilizer 
#
# Allowed values: any item id or item name (default is wood_hoe)
# 
WandItem: wood_hoe

#
# MinimumTreeDistance: optional parameter specifies minimum block distance between planted trees 
#
# Allowed values: any number bigger than 1 (set to -1 to disable, or comment out the parameter)
# 
#MinimumTreeDistance: 8

#
#
# TreeTypes: list of items that can be planted in soil(aka farmland)
#
# Example: 
#    - "apple"                      # Name of the item that must be planted and will be dropped
#        DropLikelihood: 33         # Chance an item will drop under a tree (numbers 1-100)
#        RequireFertilizer: Yes      # Yes if the tree should require occasional fertilizer
#        DropsBeforeFertilizer: 50   # Approximate number of drops before fertilizer is required
#        MaxFertilizer: 5            # Approximate number of times a tree can be fertilized (optional, or set to -1 to disable)
#        TreeType: Standard         # Type of tree that should grow from the sapling (Standard/Spruce/Birch)
#
TreeTypes:
    apple:
        DropLikelihood: 33
        RequireFertilizer: Yes
        DropsBeforeFertilizer: 50
#        MaxFertilizer: 10
        TreeType: Standard
        
    cocoa_beans:
        DropLikelihood: 33
        RequireFertilizer: Yes
        DropsBeforeFertilizer: 50
#        MaxFertilizer: 10
        TreeType: Spruce

    golden_apple:
        DropLikelihood: 5
        RequireFertilizer: Yes
        DropsBeforeFertilizer: 10
        MaxFertilizer: 5
        TreeType: Birch

    cookie:
        DropLikelihood: 33
        RequireFertilizer: Yes
        DropsBeforeFertilizer: 50
#        MaxFertilizer: 5
        TreeType: Standard
