#
# ShowErrorsInClient: toggle that determines if permissions or other error messages
#                     are displayed client-side
#
# Allowed values : Yes (shows errors to players)
#                  No  (errors only show up in server console)
# 
ShowErrorsInClient: Yes

#
# DropInterval: length of time, in seconds, between drops
#
# Allowed values: numbers bigger than 1 (no decimals)
# 
DropInterval: 60

#
#
# TreeTypes: list of items that can be planted in soil(aka farmland)
#
# Example: 
#    - "apple"                      # Name of the item that must be planted and will be dropped
#        DropLikelihood: 33         # Chance an item will drop under a tree (numbers 1-100)
#        RequireFertilzer: Yes      # Yes if the tree should require occasional fertilizer
#        DropsBeforeFertilzer: 50   # Approximate number of drops before fertilzer is required
#        TreeType: Standard         # Type of tree that should grow from the sapling (Standard/Spruce/Birch)
#
TreeTypes:
    apple:
        DropLikelihood: 33
        RequireFertilzer: Yes
        DropsBeforeFertilzer: 50
        TreeType: Standard
        
    cocoa_beans:
        DropLikelihood: 33
        RequireFertilzer: Yes
        DropsBeforeFertilzer: 50
        TreeType: Spruce

    golden_apple:
        DropLikelihood: 5
        RequireFertilzer: Yes
        DropsBeforeFertilzer: 10
        TreeType: Birch
